# Generated by Django 5.1.11 on 2025-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Indica se uma notificação sobre este alerta foi enviada.', verbose_name='Notificação Enviada'),
        ),
        migrations.AddField(
            model_name='alert',
            name='read_confirmation',
            field=models.BooleanField(default=False, help_text='Indica se o alerta foi visualizado/confirmado.', verbose_name='Confirmação de Leitura'),
        ),
    ]
