# Generated by Django 5.1.11 on 2025-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_alert_notification_sent_alert_read_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='generated_notification',
            field=models.BooleanField(default=False, help_text='Indica se foi criado um alerta.', verbose_name='Confirmação de geração de alerta'),
        ),
    ]
