# Generated by Django 5.1.11 on 2025-06-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_temperaturereading_generated_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsetting',
            name='notification_email',
            field=models.EmailField(default='teste@gmail.com', help_text='Endereço de e-mail para enviar alertas de temperatura.', max_length=254, verbose_name='Email de Notificação'),
        ),
    ]
